name: website deployment

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: jekyll build
        uses: mbursi/jekyll-build-only-action@v1.0.0
      - name: sync
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
        with:
          source: "_site/*"
          target: "/home/clients/793e7dadbc54f2acdbb0cadc4196e9b5/web"
          strip_components: 1